### ISSUE TITLE
建议加个docker版

### ISSUE THREAD

**Issue by duansheli** [Jzow/flow#1]
项目当前提供了在线体验版
这种掏钱的毕竟配置不会太好，人稍微多点还卡

搭项目 本地运行 要建数据库 拉代码
有docker的话 可以快速启动一个体验版

**Comment by ecnice** [comment]
嗯嗯&nbsp; 你说的太好了，docker我不怎么会哦，你会吗？加一下我好友，咱们一起把这个弄一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ecnice/flow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月3日(星期四) 下午5:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ecnice/flow] 建议加个docker版 (#1)





 
项目当前提供了在线体验版
 这种掏钱的毕竟配置不会太好，人稍微多点还卡
 
搭项目 本地运行 要建数据库 拉代码
 有docker的话 可以快速启动一个体验版

**Comment by ecnice** [comment]
好的我看看

**Comment by duansheli** [comment]
@ecnice docker镜像的制作不一定需要写 DockerFile 
也可以是 docker commit的 方式提交黑盒镜像

**Comment by ecnice** [comment]
好的已经在弄，估计就这几天搞上去




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月4日(星期五) 晚上7:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ecnice/flow] 建议加个docker版 (#1)





 
@ecnice docker镜像的制作不一定需要写 DockerFile
 也可以是 docker commit的 方式提交黑盒镜像
