### ISSUE TITLE
前端 flow-front-ui 启动访问 报错

### ISSUE THREAD

**Issue by hcxiaoliu** [Jzow/flow#3]
![截图](https://user-images.githubusercontent.com/49744117/121140536-88ad1600-c86c-11eb-8b06-86a87e2de2ed.png)

 http://localhost:3200/ 访问 就一直转圈圈，报截图的错 没有人遇到嘛 求解

**Comment by ecnice** [comment]
你看看是不是你的秘钥修改了，你看看在配置文件中


dragon.flow.api.app-sn=portal
dragon.flow.api.app-secret-key=K9909Jszc%YcleRr50c9aRO88q5QdxK#~0XeJz8FU89092MA5ytwyE%bFTL0MUwF
你看看和数据库是不是一样的
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ecnice/flow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月8日(星期二) 下午3:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ecnice/flow] 前端 flow-front-ui 启动访问 报错 (#3)





 

 
http://localhost:3200/ 访问 就一直转圈圈，报截图的错 没有人遇到嘛 求解

**Comment by hcxiaoliu** [comment]
![企业微信截图_16232202981928](https://user-images.githubusercontent.com/49744117/121306730-c88a0100-c931-11eb-8aae-7a117e099fc3.png)
都没有动过，，秘钥都是一样的，就还是那个错

**Comment by xietongjian** [comment]
> ![企业微信截图_16232202981928](https://user-images.githubusercontent.com/49744117/121306730-c88a0100-c931-11eb-8aae-7a117e099fc3.png)
> 都没有动过，，秘钥都是一样的，就还是那个错

前端 flow-front-ui 调的是flow-front-rest提供的Rest接口，flow-front-rest又调用了flow-admin提供出来的接口。  
所以你需要启动flow-admin（com.dragon.flow.main.FlowAdminApplication）和flow-front-rest（com.dragon.flow.main.FlowFrontApplication）这两个java应用。

**Comment by hcxiaoliu** [comment]
后台两个都启动成功了，我后台和门户都可以访问成功，，就是前端ui访问不起来

**Comment by ecnice** [comment]
报什么错呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月16日(星期三) 下午2:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ecnice/flow] 前端 flow-front-ui 启动访问 报错 (#3)





 
后台两个都启动成功了，我后台和门户都可以访问成功，，就是前端ui访问不起来

**Comment by hcxiaoliu** [comment]
就是一开始问的那个，上面有截图

**Comment by xietongjian** [comment]
> 就是一开始问的那个，上面有截图

浏览器及版本是什么？

**Comment by hcxiaoliu** [comment]
Google Chrome  版本 73.0.3683.86（正式版本） （64 位）

**Comment by xietongjian** [comment]
> Google Chrome 版本 73.0.3683.86（正式版本） （64 位）

本地开发使用了可选链语法。请使用最新版的谷歌浏览器开发。
![image](https://user-images.githubusercontent.com/16096832/122342173-de717480-cf76-11eb-9784-34aa121d92e7.png)

**Comment by hcxiaoliu** [comment]
卧槽，巨无情，，浏览器版本问题  建议在前端说明文件 加上版本标注   哈哈 ，防止人入坑

**Comment by xietongjian** [comment]
> 卧槽，巨无情，，浏览器版本问题 建议在前端说明文件 加上版本标注 哈哈 ，防止人入坑

你浏览器版本太低了，73.xx到91.xx，有多少年没升级了。

**Comment by hcxiaoliu** [comment]
这家公司两年 哈哈

**Comment by xietongjian** [comment]
浏览器版本问题，先关闭了。
